spring.application.name=order-service
server.port=8081

# DataSource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/foodtech_orders
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SQL init (data.sql se ejecuta después de Hibernate DDL)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
